export MINECRAFT_HOST=127.0.0.1 MINECRAFT_PORT=25566 MINECRAFT_OWNER=eduardo MINECRAFT_PROFILE=vanilla1201 MINECRAFT_LAN_ANNOUNCE=0
export STATUS_SERVER=0 MBOT_VIEWER_PORT=0 MBOT_INVENTORY_PORT=0
export MBOT_LAYA_SHADOW=0 MBOT_JULIA_SHADOW=1 JULIA_PLAYER_LOOP_URL=http://127.0.0.1:8769/choose
export JULIA_SHADOW_LOG=/tmp/run/julia-shadow.jsonl JULIA_SHADOW_TIMEOUT_MS=4000
export COLONY_EVENT_LOG=/tmp/run/colony-events.jsonl COLONY_PROOF_FILE=/tmp/run/colony-proof.json COLONY_STATE_FILE=/tmp/run/colony-state.json
export MEMORY_FILE=/tmp/run/memory.json MBOT_TASK_CHECKPOINT_FILE=/tmp/run/checkpoint.json
export JULIA_SHADOW_MAX_CONCURRENT=4
